library widgets;

import 'package:cached_network_image/cached_network_image.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:groceries/utils/constants/app_colors.dart';
import 'package:groceries/utils/constants/app_fonts.dart';
import 'package:groceries/utils/constants/assets.gen.dart';
import 'package:groceries/utils/extenstions/app_extensions.dart';
import 'package:smooth_page_indicator/smooth_page_indicator.dart';

part 'cached_image.dart';
part 'next_arrow_icon.dart';
part 'page_indicator.dart';
part 'primary_box.dart';
part 'buttons_loading_indicator.dart';
part 'app_text_field.dart';
part 'app_snack_bars.dart';
part 'app_loading_indicator.dart';
part 'app_bottom_navigation_bar.dart';
part 'bottom_sheet_button.dart';
part 'tile_button.dart';
part 'animations/down_fade_in_animation.dart';
part 'animations/fade_in_animation.dart';
part 'animations/left_fade_in_animation.dart';
part 'animations/right_fade_in_animation.dart';
part 'animations/up_fade_in_animation.dart';
part 'other_options_text_button.dart';
