include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer: 
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    sort_pub_dependencies: false
    public_member_api_docs: false
    one_member_abstracts: false
