include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    flutter_style_todos: false
    sort_pub_dependencies: false
    prefer_final_locals: false
    public_member_api_docs: false
