include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer: 
# linter:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    sort_pub_dependencies: false
    public_member_api_docs: false
    use_if_null_to_convert_nulls_to_bools: false
