name: groceries
version: 1.0.0+0
repository: https://github.com/FarisArmoush/groceries
issue_tracker: https://github.com/FarisArmoush/groceries/issues
topics: [clean-code, clean-architecture, flutter, bloc]

publish_to: none
description: Groceries Mobile Application
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  groceries_theme:
    path: app_theme
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.15.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  firebase_auth: ^4.2.4
  firebase_core: ^2.25.1
  firebase_crashlytics: ^3.3.0
  firebase_remote_config: ^4.3.9
  firebase_storage: ^11.0.10
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.6
  formz: ^0.7.0
  freezed_annotation: ^2.2.0
  go_router: ^14.0.0
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  shared_preferences: ^2.0.16
  injectable: ^2.3.2
  get_it: ^7.6.7
  faker: ^2.1.0
  wolt_modal_sheet: ^0.5.0
  talker_flutter: ^4.1.3
  talker_bloc_logger: ^4.1.3

dev_dependencies:
  build_runner: ^2.4.8
  bloc_test: ^9.1.1
  injectable_generator: ^2.4.1
  very_good_analysis: ^5.0.0+1
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.3.1
  freezed: ^2.4.0
  flutter_test: 
    sdk: flutter

flutter_gen: 
  output: lib/utils/constants/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
