name: groceries
version: 1.0.0+1
repository: https://github.com/FarisArmoush/groceries
issue_tracker: https://github.com/FarisArmoush/groceries/issues


publish_to: none
description: an amazing app
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  faker: ^2.1.0
  firebase_auth: ^4.2.4
  firebase_analytics: ^10.4.2
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.3.0
  firebase_database: ^10.0.9
  firebase_performance: ^0.9.2+2
  firebase_remote_config: ^4.2.0
  firebase_storage: ^11.0.10
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.6
  formz: ^0.6.0
  go_router: ^10.0.0
  http: ^1.1.0
  image_picker: ^1.0.0
  shared_preferences: ^2.0.16
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.7
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  bloc_test: ^9.1.1
  very_good_analysis: ^5.0.0+1
  json_serializable: ^6.6.1
  flutter_native_splash: ^2.0.5
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.0

flutter_native_splash:
  background_image: assets/icons/splashBackground.png
  android_gravity: fit
  ios_content_mode: scaleAspectFill
  android: true
  ios: true

flutter_gen: 
  output: lib/utils/constants/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
  fonts:
    - family: PoppinsThin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: PoppinsBlack
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf

    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf

    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: NotoSansArabicThin
      fonts:
        - asset: assets/fonts/NotoSansArabic-Thin.ttf

    - family: NotoSansArabicRegular
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf

    - family: NotoSansArabicExtraBold
      fonts:
        - asset: assets/fonts/NotoSansArabic-ExtraBold.ttf

    - family: NotoSansArabicBold
      fonts:
        - asset: assets/fonts/NotoSansArabic-Bold.ttf

    - family: NotoSansArabicBlack
      fonts:
        - asset: assets/fonts/NotoSansArabic-Black.ttf

    - family: NotoSansArabicExtraLight
      fonts:
        - asset: assets/fonts/NotoSansArabic-ExtraLight.ttf

    - family: NotoSansArabicLight
      fonts:
        - asset: assets/fonts/NotoSansArabic-Light.ttf

    - family: NotoSansArabicMedium
      fonts:
        - asset: assets/fonts/NotoSansArabic-Medium.ttf

    - family: NotoSansArabicSemiBold
      fonts:
        - asset: assets/fonts/NotoSansArabic-SemiBold.ttf
