name: groceries
version: 1.0.0+1
publish_to: none
description: an amazing app
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  firebase_storage: ^11.0.10
  firebase_remote_config: ^4.2.0
  cloud_firestore: ^4.3.1
  argon_buttons_flutter: ^1.1.0
  carousel_slider: ^4.1.1
  flutter_svg: ^1.0.3
  smooth_page_indicator: ^1.0.0+2
  flutter_speed_dial: ^6.0.0
  flutter_staggered_animations: ^1.0.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  faker: ^2.1.0
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.16
  image_picker: ^0.8.6
  cached_network_image: ^3.2.3
  go_router: ^7.0.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  # connectivity_plus: ^4.0.0
  http: ^0.13.5
  formz: ^0.4.1
  bloc: ^8.1.1
  google_sign_in: ^6.1.0
  email_validator: ^2.1.17
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.0
  firebase_crashlytics: ^3.3.0

dev_dependencies:
  build_runner:
  very_good_analysis: ^4.0.0+1
  json_serializable: ^6.6.1
  flutter_native_splash: ^2.0.5
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_image: assets/icons/splashBackground.png
  android_gravity: fit
  ios_content_mode: scaleAspectFill
  android: true
  ios: true

flutter_gen: 
  output: lib/utils/constants/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
  fonts:
    - family: PoppinsThin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: PoppinsBlack
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf

    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf

    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf




    - family: NotoSansArabicThin
      fonts:
        - asset: assets/fonts/NotoSansArabic-Thin.ttf

    - family: NotoSansArabicRegular
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf

    - family: NotoSansArabicExtraBold
      fonts:
        - asset: assets/fonts/NotoSansArabic-ExtraBold.ttf

    - family: NotoSansArabicBold
      fonts:
        - asset: assets/fonts/NotoSansArabic-Bold.ttf

    - family: NotoSansArabicBlack
      fonts:
        - asset: assets/fonts/NotoSansArabic-Black.ttf

    - family: NotoSansArabicExtraLight
      fonts:
        - asset: assets/fonts/NotoSansArabic-ExtraLight.ttf

    - family: NotoSansArabicLight
      fonts:
        - asset: assets/fonts/NotoSansArabic-Light.ttf

    - family: NotoSansArabicMedium
      fonts:
        - asset: assets/fonts/NotoSansArabic-Medium.ttf

    - family: NotoSansArabicSemiBold
      fonts:
        - asset: assets/fonts/NotoSansArabic-SemiBold.ttf

