name: groceries
version: 1.0.0+0
repository: https://github.com/FarisArmoush/groceries
issue_tracker: https://github.com/FarisArmoush/groceries/issues
topics: [clean-code, clean-architecture, flutter, bloc]

publish_to: none
description: Groceries Mobile Application
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^5.0.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  faker: ^2.1.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_remote_config: ^5.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  formz: ^0.7.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.7
  groceries_theme:
    path: app_theme
  go_router: ^14.0.0
  hive: ^2.2.3
  image_picker: ^1.0.7
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  path_provider: ^2.1.3
  shimmer: ^3.0.0
  shared_preferences: ^2.0.16
  talker_bloc_logger: ^4.1.3
  talker_flutter: ^4.1.3
  wolt_modal_sheet: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.8
  bloc_test: ^9.1.1
  flutter_gen_runner: ^5.3.1
  flutter_test: 
    sdk: flutter
  freezed: ^2.4.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.6.1
  very_good_analysis: ^5.0.0+1

flutter_gen: 
  output: lib/presentation/constants/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
