import 'package:flutter_test/flutter_test.dart';
import 'package:groceries/utils/constants/fonts.gen.dart';

void main() {
  group('FontFamily', () {
    test('Check font families', () {
      expect(
        FontFamily.notoSansArabicBlack,
        equals('NotoSansArabicBlack'),
      );
      expect(
        FontFamily.notoSansArabicBold,
        equals('NotoSansArabicBold'),
      );
      expect(
        FontFamily.notoSansArabicExtraBold,
        equals('NotoSansArabicExtraBold'),
      );
      expect(
        FontFamily.notoSansArabicExtraLight,
        equals('NotoSansArabicExtraLight'),
      );
      expect(
        FontFamily.notoSansArabicLight,
        equals('NotoSansArabicLight'),
      );
      expect(
        FontFamily.notoSansArabicMedium,
        equals('NotoSansArabicMedium'),
      );
      expect(
        FontFamily.notoSansArabicRegular,
        equals('NotoSansArabicRegular'),
      );
      expect(
        FontFamily.notoSansArabicSemiBold,
        equals('NotoSansArabicSemiBold'),
      );
      expect(
        FontFamily.notoSansArabicThin,
        equals('NotoSansArabicThin'),
      );
      expect(
        FontFamily.poppinsBlack,
        equals('PoppinsBlack'),
      );
      expect(
        FontFamily.poppinsBold,
        equals('PoppinsBold'),
      );
      expect(
        FontFamily.poppinsExtraBold,
        equals('PoppinsExtraBold'),
      );
      expect(
        FontFamily.poppinsExtraLight,
        equals('PoppinsExtraLight'),
      );
      expect(
        FontFamily.poppinsLight,
        equals('PoppinsLight'),
      );
      expect(
        FontFamily.poppinsMedium,
        equals('PoppinsMedium'),
      );
      expect(
        FontFamily.poppinsRegular,
        equals('PoppinsRegular'),
      );
      expect(
        FontFamily.poppinsSemiBold,
        equals('PoppinsSemiBold'),
      );
      expect(
        FontFamily.poppinsThin,
        equals('PoppinsThin'),
      );
    });
  });
}
