name: groceries_app_ui
version: 1.0.0+1
repository: https://github.com/FarisArmoush/groceries
issue_tracker: https://github.com/FarisArmoush/groceries/issues

publish_to: none
description: an amazing app
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.6
  easy_localization: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.8
  very_good_analysis: ^5.0.0+1
  flutter_gen_runner: ^5.3.1
  flutter_test: 
    sdk: flutter
  test: ^1.24.1

flutter_gen: 
  output: lib/src/constants/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  fonts:
    - family: PoppinsThin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: PoppinsBlack
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf

    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf

    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: NotoSansArabicThin
      fonts:
        - asset: assets/fonts/NotoSansArabic-Thin.ttf

    - family: NotoSansArabicRegular
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf

    - family: NotoSansArabicExtraBold
      fonts:
        - asset: assets/fonts/NotoSansArabic-ExtraBold.ttf

    - family: NotoSansArabicBold
      fonts:
        - asset: assets/fonts/NotoSansArabic-Bold.ttf

    - family: NotoSansArabicBlack
      fonts:
        - asset: assets/fonts/NotoSansArabic-Black.ttf

    - family: NotoSansArabicExtraLight
      fonts:
        - asset: assets/fonts/NotoSansArabic-ExtraLight.ttf

    - family: NotoSansArabicLight
      fonts:
        - asset: assets/fonts/NotoSansArabic-Light.ttf

    - family: NotoSansArabicMedium
      fonts:
        - asset: assets/fonts/NotoSansArabic-Medium.ttf

    - family: NotoSansArabicSemiBold
      fonts:
        - asset: assets/fonts/NotoSansArabic-SemiBold.ttf
