name: groceries_theme
version: 1.0.0+0
repository: https://github.com/FarisArmoush/groceries
issue_tracker: https://github.com/FarisArmoush/groceries/issues

publish_to: none
description: Groceries theme configuration
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  very_good_analysis: ^5.0.0+1
  flutter_gen_runner: ^5.3.1
  flutter_test: 
    sdk: flutter

flutter_gen: 
  output: lib/src/constants/

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
